[package]
name = "day25ui"
version = "0.1.0"
authors = ["vescoc <claudio.vesco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day25 = { path = "../day25" }
yew = "0.10"
stdweb = "0.4"
